### ISSUE TITLE
Language files names on Linux

### ISSUE THREAD

**Issue by chaloman** [scoumbourdis/grocery-crud-codeigniter-4#11]
There is a problem when GC load language files.

Ex.
include(assets/grocery_crud/languages/english.php): failed to open stream: No such file or directory

This is because language files have capitalized names but GC uses names in lowercase. This fails in linux.

**Comment by scoumbourdis** [comment]
Fixed for the latest version. I've also updated the page: https://www.grocerycrud.com/downloads/

Thanks for opening the issue.

Regards
Johnny
