### ISSUE TITLE
setRelationNtoN like enum list ?

### ISSUE THREAD

**Issue by Slobug** [scoumbourdis/grocery-crud-codeigniter-4#17]
Hi,

Thank for this library !

I can't get the same display as with the previous version.
I know the priority no longer exists but I didn't think it would change the general display of the Relation option.

Instead of having a list of terms on the right that I can add to the list on the left, I have the equivalent of an "enum" field.

Is this normal? Is it under development?
I admit that this option is essential for my activities.

Thank you in advance for your answer.

**Comment by Slobug** [comment]
![GC_issue](https://user-images.githubusercontent.com/18593182/100586436-74052980-32ef-11eb-8b8e-8413980a80f1.PNG)
![GC_issue2](https://user-images.githubusercontent.com/18593182/100586447-78c9dd80-32ef-11eb-8a9f-e4fa47cf20b6.PNG)

**Comment by scoumbourdis** [comment]
Hello @Slobug ,

Unfortunately this functionality was removed from the latest version of Grocery CRUD. This was using the jQuery plugin multiselect: https://github.com/michael/multiselect that is no longer actively developed and I had many issues when I was using it. Some of them was duplicates additions, the ability to not be able to add an item to the left... e.t.c.

Regards
Johnny

**Comment by Slobug** [comment]
Hello Johnny and thank you for your answer,

I would just like to know if you are planning to implement a similar
functionality in the future?
Or, is it a feature that you are thinking of giving up for good?

Thank you and have a nice day,
Slobug [by deepl ;O)]

**Comment by scoumbourdis** [comment]
**Short answer:** 🚀  
Unfortunately, I don't plan to implement this feature for 2021 but I want to implement this feature at the future.

**Very long answer:** 🍿 
The main "complain" that I am having from the users or my customers (for Grocery CRUD Enterprise) is that I don't have anywhere my roadmap and this is confusing sometimes. This year this will hopefully change! As I am creating a new website that will also have a blog it will also include some basic features that I plan every year. This is of course not limited to all the features that I will introduce but let's say it is the promise that I will give every year.

So when I am saying that it's not planned for 2021, I mean it is not a priority feature. It doesn't mean that I will definitely not do it! So to answer the second part of your question this is not a feature that I want to give up for good. This feature is also implementing the ability to order your data, something that currently is not available for N to N relation so I hope that I could implement it at the future. 

The main problem is that everything that you see is a one-man project from a person with a full-time job. If everything will go as per my initial plans(plans? 2020? lol), hopefully from 2022 I will be able to hire one person to help me so I can grow the product even further.

Soon I will to release the new website and hopefully it will have a good start about what to expect from Grocery CRUD and what not. It's been a good progress so far but I include lot of new website features such as:
- A blog  💬
- A more structured documentation ☕
- Instant search with Algolia Search 🔍
- Light and dark theme 🎨
- A new forum 💬
- All the documentation will also be on github 💻

Regards
Johnny

**Comment by Slobug** [comment]
Thank you very much for your answer and for your work.

Best personal and professional wishes for you and yours.

Regards
Slobug
