### ISSUE TITLE
Routes for add, edit, read or delete

### ISSUE THREAD

**Issue by difagume** [scoumbourdis/grocery-crud-codeigniter-4#2]
Hi, the main interface of Grocery Crud loads well with the data I have in the table, but I have problems when trying to add, edit or read a record and I think it's because of the routes in Routes.php.

The current route is like this:

`$routes->get('example', 'Examples::customers_management');`

the errors it shows me are:

Controller or its method is not found: App\Controllers\Example::add
Controller or its method is not found: App\Controllers\Example::read
Controller or its method is not found: App\Controllers\Example::edit

Please, if you could just point me in the right direction.

Thank you very much.

I'm using CodeIgniter: framework-4.0.2 and this repository for Grocery Crud

**Comment by scoumbourdis** [comment]
I personally am using the below line:

     $routes->setAutoRoute(true);

That by the way comes by default. This auto route will make your example work. Instead though having this URL: http://yourwebsite.com/example you will have this: http://yourwebsite.com/examples/customers_management

I hope it helped.

Regards
Johnny
