### ISSUE TITLE
Throwing Exceptions in wrong namespace.

### ISSUE THREAD

**Issue by sfadschm** [scoumbourdis/grocery-crud-codeigniter-4#3]
Hey Johnny,
thanks for the great work! I just implemented the current directory into cI4 this morning and so far, most things CRUD-related seem to be working.
However, throwing exceptions is not yet working, since in the GroceryCrud.php library, the namespace 'App/Libraries' is defined, which does not seem to have an 'Exception' class.
I fixed this for now by simply adding
 `use Exception;`
after the namespace definition in the library file.

Please correct me if I'm wrong here.
Cheers
Alex

**Comment by scoumbourdis** [comment]
You are absolutely right! Thanks for the feedback and I've just updated the code with your suggestion :)
