### ISSUE TITLE
Some flaws in the assets folder

### ISSUE THREAD

**Issue by sfadschm** [scoumbourdis/grocery-crud-codeigniter-4#5]
Hey Johnny,
great to see the project in a working state officially now :)
Here is some warning that I got from the assets:

In file
  _public\assets\grocery_crud\languages\arabic.php_
the semicolon is missing in line 91.

In
  _public\assets\grocery_crud\texteditor\ckeditor\plugins\uicolor\yui\assets\yui.css_
in line 6, a CSS hack is used:

`*html .cke_uicolor_picker ...`

This fails all validation. I would assume, that

`* html .cke_uicolor_picker ...`

would be the right choice, but am not sure how the rule is supposed to behave.

This however, is third-party I guess, but might still be worth a change if it does not need to be updated in the future.

Kind regards
Alex

**Comment by scoumbourdis** [comment]
Hello @sfadschm,

I've fixed both issues on the master branch. Thanks for the feedback and enjoy :)

Regards
Johnny
