### ISSUE TITLE
Error in the folder "assets > grocery_crud > languages"

### ISSUE THREAD

**Issue by sognonemo** [scoumbourdis/grocery-crud-codeigniter-4#8]
Hi,
I download the file from the official site for the https://github.com/scoumbourdis/grocery-crud-codeigniter-4/archive/2.0.0-BETA.zip

The installation give this error:
_include " public/assets/grocery_crud/languages/english.php" : failed to open stream: No such file or directory__
Because in the **'official download folder'** the files have the first letter all capital. Instead in the script all letters are transformed into lower.

Find this at line 3977 in APPPATH/Libraries/GroceryCrud.php

$this->language = strtolower($this->config->default_language);

**Comment by scoumbourdis** [comment]
Done! Thanks for the update. I've completely missed that as macos "forgives" the lowercase. Released also a new version.
